import { test, expect } from '@playwright/test';

/**
 * E2E test for factory import functionality
 * 
 * This test verifies that users can:
 * 1. Navigate to the import dialog
 * 2. Paste a compressed factory export string
 * 3. Import multiple factories from the export
 * 4. View and interact with the imported factory nodes
 */
test('import factory from compressed export string', async ({ page }) => {
  // Navigate to default factory view
  await page.goto('./zones/main/default-factory', { waitUntil: 'domcontentloaded' });

  // Open factory menu and navigate to import settings
  await page.getByTestId('zone-sidebar-expand-toggle').click();
  const importLink = page.getByTestId('import-factory-link');
  await importLink.waitFor();
  await importLink.click();
  
  // Switch to Import tab
  await page.getByTestId('settings-tab-import').click();

  // Paste factory export string (contains 2 factories: Nuclear Reactor and Glass Smelting setups)
  const exportString = 'H4sIAAAAAAAACu1aXW8bORL8K4t5pphmd5Pd/ZjsJpuH+M6Ifbc4BEEwkbj2ILIUjEYX598fKMeyNZaskeN7CCC/GTOu4kezWD3lDx/QVf9Yjqe5bn876+qL/BtWrno57pb1tHLVi3qxyN3ixdd2PlmOu8WLq/l1O5/4r7OLyn34UM0qV/2rrWfN8ur9fLJ4uVjkq8/T7+f0KUhSiAFCMJTKoUchoSSRmZAQUh4FcuRZEQExUlBmjLwDr3Jdu8wf3Qbl61nbjC+v8qy7o0sRrHIjNvAcUSMQACdVNwIfLVAyFBC0xMRbgLbyvMv1+LKZXaxZkIWpciNTdejh/g8qP/i7raC/t8tFeXiOa1iiGLRyoxDRnG15cxPo5biZnDTXJ811DyZp4hVMiI4oPnhzE+bH9r/P9bibt+d4B8SkkSoXFT0lMOUgypHMjaJ6okRiEgTMALfAbLKcL9vPzSy/bS4uT9u8WNwbb1LmWLkC7lGDJIAIkNiNQgAPxsYsZFFA0jagTaLT+bfc/plnua1X41jTSADCyqEF8mBkCYQJDVLhMV8Khy0IigjKQ5yt03k3/9afjTAjVQ4pkY9JRVIySsERBR9BASCaGSXcArLJcfY1z7o3yzx9n7+283FeLO7VYDBkhspFid5YTBSUJXJwpfRRFCgkJrAgO5Aq93c9XazZTubXG0cu3DEpRSlMPkIKSUJgJhVxicmbqRJoQLJIW1B6LP0qWbNgMqBUuRAUvCkERAksQMlRUG8xsYlZiJqEtuBsLt2relrPxrn9dHojXJ/eNItFM5/d/npLqowQytTQi0ThpDFikujUoo8xsJEEiMSyF3NzAOuFzpOdYoVqrKGIlYhPrCGySRlScjEGnwQlGhMHE3sccZP7zXQ5b5tJ7ssWIYQYV7IVvFgUDcJgwugiPJhuH2WT44+8qKfNrO6a+exNO796e3rLopA0atlI4yIbHFQYAZMbCSRvIUEgsyCatsH06uXBov9Vd7ldc4VIrGX/zBuUcmcyIXWjCOABggmAqHFi3oW1j/Csy/XV22ZNiUJFRgISuFEA8zFFsUTGJExpN8KeCl299W69jAYJFCoXFMp5UBRjTSkZO8LgRTiAaMCgajtJ350+vmt/5K/T3OXJmlRKWa7Ei30gi8pqMYA6JfRlH5NwkpWm7MIatJ49YgRg0VTEGcwzGSUJpCGpU0ZvIAZKgYhh51x38G88+30+m+TZYjXmtWQjBE52I9nJg5gaFUW16AKKeY2kylhe0/goYI/6fH7djM+my7b9ft7murt39pGQKaZy9hN6DBgNqTyycrmi+BhUKYWkAEG3Q/Uui6v5l3zW1eMv7+r2Ir++vqyXi1u6YixQS9WGaD4SWGQwRRIXwJJHSFEASg0z7sLa5PtzWi8WZ1d52jWzi5ft+Dz81XSXr9r5lzwrrAYSMCmnlRRE9SZF2pGiCToB80kUIShC0hQfB7xd2I/Fc34ul/yPnd9QwrL3+63hIL9aZnmf5z95Op1/G9df8n5XuHcIffAf7/+zzSund38au03inlH0OYoD3G8ZDwS9W8mhbcBes9mn+HfTllbk00keX64c2SAruc8EHsCy2+EdSrI2YUM89yDz12c4nS67edmEoeZxr+nrM9y8P8Qt7nV6fei+mxo4g8Oc3q4KvvNWg4kPcHg7WO+p1iF28UkC9vb7pJ1f5NmtqxtgEw/Wsadw/MQqDpS0pxykH8ZwoPs8WNTWhnCADgz0o7sphhra/bI6fBoPurqnTuMnN2Kf5tzC7+9mho3gGXZh71C2chSjP+ReHNh17OYY2rbsvT6HbsWuFuUnNuSuUxhwyR/Uv+yjO6wZGroWz8w6vGPqE9/rUgbY5AHt0a4iOaCpe1qd3BINaeF+jmGgsj1+y/XBX7XNLB9ymJ6wFwOv3z0O4KHBnHZ5tuoFD2wyn3TRr1vbA6mGNNs33Wq/xXg9zeOubcZN9718RCqRgasu7jXXD7vCyo1w462CvDW3Oc+LrqzbMZs5ZjO/ZDajCl7RSt0BpShYvoahV4XVp06wCL9ONDMKKMkHobI7uspHIoKnqGoqYgLlu9cvlc1I8qvKW32LhsAOhcv3xNKjkaZkz57MqPhYCjvFUmVELgCqV4IEoMlQRY/RzOHRjHm0lLQ4gICibiQavVpCjIkDB4nHcOYYzhzDmecJZ9400y63J3nS1Df3/MndBEnKbMrRN/BF4qJJ0ZvoRkLoywUlRWpjItmO1JO3+fjLrStZc6gRrGyHEXjiclcAsxiQG2mZEZoGFoUEMW1i9GKftv5vnj7At7hykqPAKXjmxBYxUExB3ShJEbBiLAME4yh9lEeCpXPcdOEre82YVFbmOXpUJmSJhkjJSQAfmEgxaiyF+ghcvxQH5mfGvvyjhZXDbhFKGap6QVCKRpFDOQSPBmjHEOsYYh1DrGOIdQyxjiHWMcQ6hljHEOsYYh1DrGOI9QuGWPe60YFd7lMW7KSeLf+ux92yzZOzejbZ24YOGUmf5AZxT//8OO8x4vvZiO+xdv85873HeQaFe08qnyF1+X9MDT/+D1mFY0/vNQAA';
  await page.getByTestId('import-textarea').fill(exportString);

  // Click import button
  await page.getByTestId('import-factories-button').click();

  // Verify imported nodes are visible in the graph
  // These test IDs are automatically generated by React Flow based on node IDs
  await expect(page.getByTestId('rf__node-NuclearReactorT22_1768051043853')).toBeVisible();
  await expect(page.getByTestId('rf__node-SpentFuelReprocessing_1768051192440')).toBeVisible();

  // Test interaction: click on nodes to select them
  await page.getByTestId('factory-controls-graph-update-button').click();
  await page.getByTestId('rf__node-GlassSmeltingArcT1WithBroken_1769071268468').click();

  // Verify the summary panel shows expected production rates
  // Uses regex for numeric values that may vary slightly
  await expect(page.getByTestId('sidebar-byproducts-list')).toMatchAriaSnapshot(`
    - img
    - text: "7.7"
    - img
    - text: "0.4"
    - img
    - text: "0.4"
    - img
    - text: "27.8"
    - img
    - text: "48.1"
    - img
    - text: "0.1"
  `);
});
